# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 240e5810171ef27485ae5d0cf14c1aeb013477711baf9e0ee3322a2df19d2cf20ae7836af4a33234efe5af7db58f552c159d58365b8aaef159ce32782d7d58cb

test:
  secret_key_base: 7f2c435c9b515f7faf0ca30dbdbf4d2c04c5abe6795c69ca9e0885c56abb6116d68394d38afd0393067477235c1c1dd3d9142e522e0f4298c6baa62c95efb753

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
